### ISSUE TITLE
24.6.12客户端无法下载视频

### ISSUE THREAD

**Issue by KevinTsangZ** [Zhouqluo/bilidown-web#3]
bilidown, IDM, evolved, 猫抓 都尝试过并无法下载
![Snipaste_2024-06-12_13-29-50](https://github.com/Zhouqluo/bilidown-web/assets/115599397/361002fb-1ff2-4a03-a4e4-11cb68d056c1)
但是bilidown网页端下载成功，后面又回客户端试试，客户端还是不行
![Uploading Snipaste_2024-06-12_13-30-05.png…]()

**Comment by Zhouqluo** [comment]
请更新至最新版本下载试试。
