### ISSUE TITLE
Not support 1080P download even I login already

### ISSUE THREAD

**Issue by 13RTK** [Zhouqluo/bilidown-web#8]
![image](https://github.com/user-attachments/assets/b566440a-bf72-479c-a4bd-6c0b2c05e843)
![image](https://github.com/user-attachments/assets/c9851211-2605-4a8c-87b4-10d1ac195083)

**Comment by Zhouqluo** [comment]
For the web version, videos released before June 2023 can be downloaded in 1080P resolution after logging in, but videos released after that only have 720P resolution after logging in. If you don't log in, you only have 360P. Details can be found in the document （https://zhouql.vip/bilibili/doc/bilidown-web-questions.html#%E7%99%BB%E5%BD%95%E4%BA%86%E4%B8%8B%E8%BD%BD%E4%B8%8D%E6%98%AF1080p）
